apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chat-service
  namespace: chat
  labels:
    app: chat-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        # Sidecar container for cloudsql-proxy to connect to CloudSql database - recommended approach by Google for GKE
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
          command:
            - /cloud_sql_proxy
            - -instances=fitcentive-dev-03:northamerica-northeast2:gke-dev-env-cloud-sql-instance:=tcp:5432
            - -credential_file=/secrets/cloudsql/credentials.json
          volumeMounts:
            - name: cloudsql-creds
              mountPath: /secrets/cloudsql
              readOnly: true
        - name: chat-service
          image: gcr.io/fitcentive-dev-03/chat:1.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: 300Mi
              cpu: "0.3"
            limits:
              memory: 500Mi
              cpu: "0.5"
          ports:
            - name: http-port
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/chat/health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/chat/health
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: internal-service-secret
            - secretRef:
                name: chat-service-service-account-credentials
            - secretRef:
                name: chat-service-cloudsql-database-url
            - secretRef:
                name: chat-service-cloudsql-database-credentials
            - secretRef:
                name: chat-service-native-auth-public-credentials
            - secretRef:
                name: chat-service-facebook-auth-public-credentials
            - secretRef:
                name: chat-service-google-auth-public-credentials
            - secretRef:
                name: chat-service-apple-auth-public-credentials
          env:
            - name: GCP_PROJECT_ID
              value: "fitcentive-dev-03"
            - name: DELETED_USER_ID
              value: "aaaaaaaa-aaaa-8bbb-8bbb-aaaaaaaaaaaa"
            - name: SECRET_KEY_BASE
              value: "+V4JJUEQH/9NgEcRJUL4hxZn6Vag1naJkSb+ms4EJeHp1tOiTFeFRZPBhcLpDtah"
            - name: PHX_HOST
              value: "api.fitcentive.xyz"
            - name: TOPIC_CHAT_ROOM_MESSAGE_SENT
              value: "chat-room-message-sent"
            - name: POOL_SIZE
              value: "20"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: cloudsql-creds
          secret:
            secretName: chat-service-cloudsql-instance-credentials
