apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: chat:1.0
          imagePullPolicy: Never
          resources:
            requests:
              memory: 300Mi
              cpu: "0.5"
            limits:
              memory: 500Mi
              cpu: "1.0"
          ports:
            - name: http-port
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/chat/health
              port: 4000
            initialDelaySeconds: 60
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /api/chat/health
              port: 4000
            initialDelaySeconds: 120
            periodSeconds: 15
          env:
            - name: NATIVE_AUTH_KEY_ID
              value: "Dhb5KyQiZHEBLrAhiYltrBLEamD4nnh61eFM4FsnGO0"
            - name: NATIVE_AUTH_PUBLIC_KEY
              value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAixbkaPx/USZN27DumqgVXCrciZyt9zZGjRgpVwJ2uIKTGW/nyUlRIP+yYnHcaCVyArHDNVf+7DCKzCdBocYGWhcFA0ERG6aWBBVBxbnfcLGGVEyxaa3GJG58iXIBgeVTYExM/roBXE6SmVZWDBZTZ7lwHT3D6KbQZBe34minZEcCBDma4VXX7CLLDlTF/PiDd4BoKcH1XuzF/0PJkGQnjNj+Z9pezbC+lCPL28mHWVqYoE2BWW2m8Pt6yi3D1CibfHaF3cjqg+DMtgTZDy8oAbjEeAPycA/KiHMNa0TBFGugXyd3UdtREmltMlDx5AU1QgP7eUmJnQYQEP+HFISS9QIDAQAB"
            - name: NATIVE_AUTH_ISSUER
              value: "https://api.vid.app/auth/realms/NativeAuth"
            - name: GOOGLE_AUTH_KEY_ID
              value: "ZK_xufw1gGfVqJ-3a4aJM9EzZRfxp1Z6_AH2fCpYvtk"
            - name: GOOGLE_AUTH_PUBLIC_KEY
              value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhZrtxOu/AVm6H001Xlthefixpf79nUqgs/jKZQzp1RS8tm3deERalaphxvFrtxju35fcEJgaXzIa+hq6yP6EnAiXTOY+MeF16unxx4jUJr/ZW+S/0Cj+c7XDYSO/aYOuOcd6M4lTuPYWQNrwDfywU8FBzd1gH98vscQ4b74BisYCRx0tl6xDwpGrrpBdPrlSeTJau6MZaYbrVrplRZXxmJxwUitS0hXhzZw5gP0380T2nvcTL2eMexm5atUG83JU74dts+Fec8wGyqGxouVAJi3rmEVBquqh1HhryM4QhCeXigIr4Qw6weAQpXtQpMYq6USv6F3B2+us29T4JmG/fwIDAQAB"
            - name: GOOGLE_AUTH_ISSUER
              value: "https://api.vid.app/auth/realms/GoogleAuth"
            - name: APPLE_AUTH_KEY_ID
              value: "qdczNS1H48MCBJ7QD0dhnv_o_BikgoN4U79--nQmxT0"
            - name: APPLE_AUTH_PUBLIC_KEY
              value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmVDJ4ZXPO09a6eHHWmke2TbBzvsLZIy7dITsJIxu3eYK5oNPF4hVZzP75AMbtSiMuHKIiEji7CulZmd7pu25nUidKNVYB4Kh66kaWsiJ6z7iqTz6Xajc25AdOiQTCk6aE8HqVKSXNULhC53ZF7uMKApEdlvEDPubpUmj/FR8oIBPwmoyovW3JUhydqcMxyplBemrwxPw9SCJhbOaBJtShiyJ+q5xQL23gltweUiVHT6UT2EkNNQpS1uBCeLNguVSEUGFDw4YYTFkKiMBEjhjfHYdeAx5dmq5hVCf2ECphIxeKrb6z3+xz5iRW4yvr7s2ix+dvnybaf11186qLHARSwIDAQAB"
            - name: APPLE_AUTH_ISSUER
              value: "https://api.vid.app/auth/realms/AppleAuth"
            - name: FACEBOOK_AUTH_KEY_ID
              value: "ReWncxo8lc4oy53iYaYGqXmoPbQByWTMrvGp98jKshE"
            - name: FACEBOOK_AUTH_PUBLIC_KEY
              value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAluPfaSgKazjCS10NXvcLIKqJrS5gbtMc2QSCQWhISB0wQ/znd11MAmVsWYNuqR7ZYt5zhFevhvx49GlTV8jo814ZOIDwqpSkl+AB0l/hOEAFuEQhAmTKAajyA8tug65N9WXv2deiHmIM6uHJj0lLt1WIMF4slRu2WueLE/KeOCrtDLOytilyipcZWyT9t3EJVHKIIrTVTQePm5BhpaV627X8oOi8unh6caUodJGHJ5i44lit7jgQd02D+fWLg4AAZXTYTjeG3KGAy92bJWfE2xVszQXzakQPzaS12dFEuUWIQoUGKKOs2pVK4g/PXtFxNBrnH3CYbVTC9QLGLlFA4wIDAQAB"
            - name: FACEBOOK_AUTH_ISSUER
              value: "https://api.vid.app/auth/realms/FacebookAuth"
            - name: DATABASE_URL
              value: "ecto://postgres:postgres@192.168.64.3:1212/postgres"
            - name: SECRET_KEY_BASE
              value: "+V4JJUEQH/9NgEcRJUL4hxZn6Vag1naJkSb+ms4EJeHp1tOiTFeFRZPBhcLpDtah"
            - name: PHX_HOST
              value: "api.vid.app"
            - name: TOPIC_CHAT_ROOM_MESSAGE_SENT
              value: "chat-room-message-sent"
            - name: GCP_CREDENTIALS
              value: |
                {
                  "type": "service_account",
                  "project_id": "fitcentive-1210",
                  "private_key_id": "4f3121258c62a15ef8839aa52d364288f77cc65d",
                  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC8H1qQvNwzVa3Y\no4nckNyaXKuNgL71xgp3lME/tARqjHaI2jL1vXETIIBhBHu42x+aF1Cqgw8JRKX3\nYoxEeg3gfrDchpA7iw99sT/nQEnaZK4FGLKbg4Pt4aSpAgSBVTpg33bmYJOqY51e\nyIOmLotTqg1NviHwzaV0CG4BV1R8M1Fb0OFxDb22Y6RRww5StvpcQK3cDOHvnEfN\nzoKKJds7ifLM/KrUisLmAb863TZTwm8wgNuSrAPgDe8rLMi00ftGLD4IL+OF2ua+\nRJ0Pxdf5R7GYwAdEmU+MYpF6A0/slBCSzF5RtdNtCJgii5A4ymnV6EGbwlxm4HrV\n1G8/DTJZAgMBAAECggEAN20RdOWAB0vuHY8JdkfkB0LYdKeDG8yOlu7oBQnX50Cd\nR/Lp4sc/AoCn8m2suiktZWwLI0Hb80IbmAicBSzk28jX+RFYe4KcPM81Yb/qQoM5\nVl0ReopEG5lIt1bV1vkyawpL8NJxj1ksK5nuV88M08idhNNJEra0UbyOFK0TQkgm\nGkaQhMO5xjbNIzgCekL4Jw8265MLX/FFBKrkN2aXZumszdqYgh1RU3WLuA7rqGWF\nuxbPIFThBkkacr2SX0ur9I5amTRDTJ/ZZc59wVjjMnir9bN5xGRSg1htjOShXT/q\nUgJ/dYqiR9dJpvbi1vyoAQcQ51gMRK9Y/ddn1dwIJQKBgQD4RmY8D2tjCFcfnLbZ\nknnTnsO9TQHhnfznkZVAMYLopgH/t3hTg0h+ZcJueo13Ltn4NLBErxIQFOZU1zYo\nsdQLQ0X6hpK/ugjmMWsgNy9BbLK6qO3yAJ4BgLXWT5aJ1aRIEBwyPLYtCPz4Nm7N\np69X0oy2+iyS0o89f6/Rd/kTLwKBgQDB+dFVHNkdu7yiRb6H9HhAE3LPj+6GCjTB\nTGLuSUXg6uzcRe4b8DmycJdcIcNY9cXzzNxfe1OdEgRyK97npZM07967Jyfnw+B0\nAYkHwMFFlzQOQLcwgzwVxP8r0LSF5UgPp362oNfuYDTPm7VSvJlQVIkp14UCAl1I\nPtEbqNNQ9wKBgED6K8eMQY6poCOl4DURINFBu/jPLq7dqlLwxx8F1j0NNXi3i8ZP\nlal++GPxrxSCLonHQFq5dwC+d4m8yW/dGqHX+XiXv9Bt3+ZfCKplxvhYem5fx+aO\nQswh43UzXzKzt0sk7Dw5p3Qh5hMQK++m8z0I3csFrqS+dr6hrGImBAoBAoGAHi5V\nkM2lRogQaJs7cwHpt+aOxZbagQaTgMP23KaP9df3tKo4yyYMhCQamN4z++J5w15L\np5uTveuwv2buDtLnXaQ43pvQDLKgeMxIWul16PMGyXTuS+EPdz+oiFO30uGC3dSs\n1ZOfJVrYvLi4dMAdhq8wjE8ZRd/CTdxgQtJ41q8CgYEAnWtuh73kM5yasnBOl6XA\nB2uTaja0Y3T2fgvcmAScoyMnl+dySq9Xr36RAo5VVptvAPRUVijDKs5Km2sDULKf\nEJjX+HT5+omnQ0Ndzsn0Dp6ne+i6yvoXSyc1X3wzjBSZ0/POw+n2HY/g8kOHjWKv\nl6GGLjHPdoBoOZZtDC1GJPE=\n-----END PRIVATE KEY-----\n",
                  "client_email": "chat-service@fitcentive-1210.iam.gserviceaccount.com",
                  "client_id": "118361710915600212992",
                  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                  "token_uri": "https://oauth2.googleapis.com/token",
                  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/chat-service%40fitcentive-1210.iam.gserviceaccount.com"
                }

